# golangci-lint configuration
# See https://golangci-lint.run/usage/configuration/

# Configuration version (required for golangci-lint v2)
version: "2"

run:
  # Include test files
  tests: true
  
  # Modules download mode
  modules-download-mode: readonly

# Output configuration (v2 format)
output:
  formats:
    text:
      path: stdout
      colors: true
      print-issued-lines: true
      print-linter-name: true

# Linters configuration (v2 format)
linters:
  # Enabled linters
  enable:
    - errcheck      # Check for unchecked errors
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Static analysis (includes gosimple, stylecheck, and unused in v2)
    - unused        # Check for unused code
    - gocyclo       # Cyclomatic complexity
    - misspell      # Find spelling mistakes
    - goconst       # Find repeated strings
    - dupl          # Code clone detection
    - lll           # Long lines
    - nakedret      # Naked returns
    - prealloc      # Slice preallocation
    - revive        # Fast, configurable linter
    - gosec         # Security checks

  # Linter settings
  settings:
    errcheck:
      # Check type assertions
      check-type-assertions: true
      # Check blank assignments
      check-blank: true
      
    govet:
      # Enable all analyzers
      enable-all: true
      
    gocyclo:
      # Minimal cyclomatic complexity to report
      min-complexity: 15
      
    dupl:
      # Minimum token count to detect duplicate code
      threshold: 100
      
    goconst:
      # Minimal length of string constant
      min-len: 3
      # Minimum occurrences to report
      min-occurrences: 3
      
    misspell:
      # Locale for spell checking (US for consistency with Go ecosystem)
      locale: US
      
    lll:
      # Max line length
      line-length: 120
      
    gocritic:
      # Enable multiple checks by tags
      enabled-tags:
        - diagnostic
        - style
        - performance
        - experimental
        - opinionated

  # Linter exclusions
  exclusions:
    rules:
      # Exclude some linters from running on tests files
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
          - lll
      
      # Exclude known issues in generated code
      - path: vendor/
        linters:
          - all
      
      # Allow UK spellings in specific contexts (sanitised is acceptable security term)
      - text: '`sanitised` is a misspelling of `sanitized`'
        linters:
          - misspell

# Formatters configuration (v2 format - gofmt, gofumpt, goimports moved here)
formatters:
  enable:
    - gofmt         # Check formatting
    - goimports     # Check imports formatting
  
  settings:
    goimports:
      # Put local imports after third-party packages
      local-prefixes:
        - github.com/bancey/document-smbrelay-service
      
    gofmt:
      # Simplify code
      simplify: true

# Issues configuration
issues:
  # Maximum issues count per one linter
  max-issues-per-linter: 50
  
  # Maximum count of issues with the same text
  max-same-issues: 3

