# Development-focused Docker Compose configuration
# This setup mounts local code and enables hot-reloading

services:
  # SMB Server for development testing
  samba:
    image: dperson/samba:latest
    container_name: smb-server-dev
    ports:
      - "445:445"
      - "139:139"
    environment:
      - USER=testuser;testpass
      - SHARE=testshare;/share;yes;no;no;testuser;testuser;;Test Share
      - SHARE2=documents;/documents;yes;no;no;testuser;testuser;;Documents Share
      - WORKGROUP=WORKGROUP
    volumes:
      - samba-data-dev:/share
      - samba-documents:/documents
    networks:
      - smb-network
    restart: unless-stopped

  # Document SMB Relay Service with hot-reload
  smb-relay:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: smb-relay-service-dev
    ports:
      - "8080:8080"
    environment:
      - SMB_SERVER_NAME=samba
      - SMB_SERVER_IP=samba
      - SMB_SHARE_NAME=testshare
      - SMB_USERNAME=testuser
      - SMB_PASSWORD=testpass
      - SMB_DOMAIN=
      - SMB_PORT=445
      - SMB_AUTH_PROTOCOL=ntlm
      - LOG_LEVEL=DEBUG
    volumes:
      # Mount source code for hot-reload
      - ./app:/app/app:ro
    networks:
      - smb-network
    depends_on:
      - samba
    restart: unless-stopped
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]

networks:
  smb-network:
    driver: bridge

volumes:
  samba-data-dev:
    driver: local
  samba-documents:
    driver: local
