version: '3.8'
services:
  smbrelay:
    image: https://hmctspublic.azurecr.io/webcactus/smbrelay:main
    container_name: document-smb-relay
    ports:
      - "8080:8080"
    environment:
      SMB_SERVER_NAME: ${SMB_SERVER_NAME}
      SMB_SERVER_IP: ${SMB_SERVER_IP}
      SMB_SHARE_NAME: ${SMB_SHARE_NAME}
      SMB_USERNAME: ${SMB_USERNAME}
      SMB_PASSWORD: ${SMB_PASSWORD}
      SMB_DOMAIN: ${SMB_DOMAIN:-}
      SMB_PORT: ${SMB_PORT:-445}
      SMB_BASE_PATH: ${SMB_BASE_PATH:-}
      OTEL_ENABLED: "true"
      OTEL_SERVICE_NAME: document-smbrelay-service
      OTEL_SERVICE_VERSION: ${SERVICE_VERSION:-1.0.0}
      OTEL_EXPORTER_OTLP_ENDPOINT: otel-collector:4318
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    depends_on:
      otel-collector:
        condition: service_healthy
    networks:
      - smbrelay-network
    restart: unless-stopped
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    ports:
      - "4318:4318"
      - "4317:4317"
      - "13133:13133"
    environment:
      APPLICATIONINSIGHTS_CONNECTION_STRING: ${APPLICATIONINSIGHTS_CONNECTION_STRING}
    configs:
      - source: otel-config
        target: /etc/otelcol-contrib/config.yaml
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:13133/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - smbrelay-network
    restart: unless-stopped

configs:
  otel-config:
    content: |
      # OpenTelemetry Collector Configuration for Azure Application Insights
      receivers:
        otlp:
          protocols:
            http:
              endpoint: 0.0.0.0:4318
            grpc:
              endpoint: 0.0.0.0:4317

      processors:
        batch:
          timeout: 10s
          send_batch_size: 1024
        memory_limiter:
          check_interval: 1s
          limit_mib: 512
        resourcedetection:
          detectors: [env, system, docker]
          timeout: 5s

      exporters:
        azuremonitor:
          connection_string: "$${APPLICATIONINSIGHTS_CONNECTION_STRING}"
        logging:
          loglevel: info

      service:
        pipelines:
          traces:
            receivers: [otlp]
            processors: [memory_limiter, resourcedetection, batch]
            exporters: [azuremonitor]
          metrics:
            receivers: [otlp]
            processors: [memory_limiter, resourcedetection, batch]
            exporters: [azuremonitor]
          logs:
            receivers: [otlp]
            processors: [memory_limiter, resourcedetection, batch]
            exporters: [azuremonitor]
        extensions: [health_check]

      extensions:
        health_check:
          endpoint: 0.0.0.0:13133

networks:
  smbrelay-network:
    driver: bridge
