services:
  # SMB Server (simulates a file server or DFS target)
  samba:
    image: dperson/samba:latest
    container_name: smb-server
    ports:
      - "445:445"
      - "139:139"
    environment:
      # Create a user: username;password
      - USER=testuser;testpass
      # Create a share: name;path;browseable;readonly;guest;users;admins;writelist;comment
      - SHARE=testshare;/share;yes;no;no;testuser;testuser;;Test Share
      # Workgroup/domain
      - WORKGROUP=WORKGROUP
    volumes:
      - samba-data:/share
    networks:
      - smb-network
    restart: unless-stopped

  # Document SMB Relay Service
  smb-relay:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smb-relay-service
    ports:
      - "8080:8080"
    environment:
      - SMB_SERVER_NAME=samba
      - SMB_SERVER_IP=samba
      - SMB_SHARE_NAME=testshare
      - SMB_USERNAME=testuser
      - SMB_PASSWORD=testpass
      - SMB_DOMAIN=
      - SMB_PORT=445
      - SMB_AUTH_PROTOCOL=ntlm
      - LOG_LEVEL=INFO
    networks:
      - smb-network
    depends_on:
      - samba
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      start_period: 10s
      retries: 3

networks:
  smb-network:
    driver: bridge

volumes:
  samba-data:
    driver: local
