name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us diagnose and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Start the service with '...'
        2. Send a request to '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs or Error Messages
      description: Please copy and paste any relevant log output or error messages
      render: shell
      placeholder: Paste logs here...

  - type: input
    id: go-version
    attributes:
      label: Go Version
      description: Output of `go version`
      placeholder: "go version go1.22.0 linux/amd64"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you running?
      placeholder: "Ubuntu 22.04, macOS 14.0, Windows 11, etc."
    validations:
      required: true

  - type: dropdown
    id: deployment
    attributes:
      label: Deployment Method
      description: How are you running the service?
      options:
        - Binary (built locally)
        - Docker container
        - Docker Compose
        - Kubernetes
        - Other
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Variables
      description: Relevant environment variables (please redact sensitive information like passwords)
      render: shell
      placeholder: |
        SMB_SERVER_NAME=myserver
        SMB_SERVER_IP=192.168.1.10
        SMB_SHARE_NAME=Documents
        LOG_LEVEL=DEBUG

  - type: textarea
    id: smb-server
    attributes:
      label: SMB Server Information
      description: Details about the SMB server you're connecting to
      placeholder: |
        - Server type: Windows Server 2019, Samba 4.x, NAS device, etc.
        - SMB protocol version: SMB2, SMB3
        - Authentication method: NTLM, Negotiate, Kerberos
        - DFS enabled: Yes/No

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or information that might help

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify the following
      options:
        - label: I have searched for existing issues that describe this problem
          required: true
        - label: I have included all relevant information above
          required: true
        - label: I have redacted sensitive information (passwords, credentials, etc.)
          required: true
