blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/bancey/document-smbrelay-service/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📚 Documentation
    url: https://github.com/bancey/document-smbrelay-service#readme
    about: Read the project documentation
  - name: 🚀 Quick Start Guide
    url: https://github.com/bancey/document-smbrelay-service/blob/main/QUICKSTART.md
    about: Get started with the service quickly
