name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
            # set commit SHA with branch prefix for branch builds
            type=ref,event=branch,suffix=-{{sha}}
            # set commit SHA with pr prefix for PR builds  
            type=ref,event=pr,suffix=-{{sha}}
            # set pr-<number> for pull requests
            type=ref,event=pr,prefix=pr-
            # set branch name for non-main branches
            type=ref,event=branch
            # set tag name for tags
            type=ref,event=tag
          labels: |
            org.opencontainers.image.title=Document SMB Relay Service
            org.opencontainers.image.description=A FastAPI service that accepts file uploads and writes them to SMB shares

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max